### ISSUE TITLE
Not sure, noticed a logfile

### ISSUE THREAD

**Issue by Sakata-MC** [Phrynohyas/eve-o-preview#150]
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'FlatLayout['EVE - Maeve Sakata']', line 35, position 1.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at EveOPreview.Configuration.Implementation.ConfigurationStorage.Load()
   at EveOPreview.Presenters.MainFormPresenter.LoadApplicationSettings()
   at EveOPreview.Presenters.MainFormPresenter.Activate()
   at EveOPreview.View.MainForm.Show()
   at EveOPreview.Presenter`1.Run()
   at EveOPreview.Program.Main()

**Comment by Phrynohyas** [comment]
Well, in this case it should just revert configuration file to its default values. Still if the app fails to start hen please send me your config file via in-game mail
